export const MOCK_PROPERTIES = [
  {
    id: '1',
    title: 'Modern 3-Bedroom Villa with Pool',
    price: 3500000,
    currency: 'ZMW',
    location: 'Leopards Hill, Lusaka',
    beds: 3,
    baths: 2,
    sqm: 450,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop',
    type: 'villa',
    listingType: 'sale',
    isVerified: true,
    isFeatured: true,
    has_borehole: true,
    has_staff_quarters: true,
    solar_capacity: 5,
    generator_capacity: 10,
    water_tank_capacity: 5000,
  },
  {
    id: '2',
    title: 'Luxury Apartment in Lagos CBD',
    price: 1200000,
    currency: 'USD',
    location: 'Victoria Island, Lagos',
    beds: 2,
    baths: 2,
    sqm: 120,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=2070&auto=format&fit=crop',
    type: 'apartment',
    listingType: 'rent',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Spacious Farm Land for Development',
    price: 850000,
    currency: 'ZAR',
    location: 'Stellenbosch, Cape Town',
    beds: 0,
    baths: 0,
    sqm: 5000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2070&auto=format&fit=crop',
    type: 'agricultural',
    listingType: 'sale',
    isVerified: false,
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Commercial Office Space in Sandton',
    price: 45000,
    currency: 'ZAR',
    location: 'Sandton, Johannesburg',
    beds: 0,
    baths: 4,
    sqm: 350,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop',
    type: 'commercial_office',
    listingType: 'rent',
    isVerified: true,
    isFeatured: false,
  },
  {
    id: '5',
    title: 'Contemporary Townhouse in Nairobi',
    price: 25000000,
    currency: 'KES',
    location: 'Westlands, Nairobi',
    beds: 4,
    baths: 3,
    sqm: 280,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
    type: 'townhouse',
    listingType: 'sale',
    isVerified: true,
    isFeatured: false,
  },
  {
    id: '6',
    title: 'Beachfront Plot for Luxury Villa',
    price: 450000,
    currency: 'USD',
    location: 'East Legon, Accra',
    beds: 0,
    baths: 0,
    sqm: 1200,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop',
    type: 'vacant_land',
    listingType: 'auction',
    isVerified: true,
    isFeatured: false,
  },
  {
    id: '7',
    title: 'Charming Cottage in Livingstone',
    price: 1800,
    currency: 'ZMW',
    location: 'Livingstone Central',
    beds: 2,
    baths: 1,
    sqm: 85,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop',
    type: 'house',
    listingType: 'rent',
    isVerified: false,
    isFeatured: false,
  },
  {
    id: '8',
    title: 'Industrial Warehouse with 3-Phase Power',
    price: 12000000,
    currency: 'NGN',
    location: 'Ikeja Industrial Estate, Lagos',
    beds: 0,
    baths: 2,
    sqm: 1500,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070&auto=format&fit=crop',
    type: 'warehouse',
    listingType: 'sale',
    isVerified: true,
    isFeatured: false,
  }
]
